### ISSUE TITLE
Store name missing in plugin list

### ISSUE THREAD

**Issue by cat24max** [alliance-apps/VeniceRCON-backend#13]
The "store" attribute is not being printed out when requesting store content.

GET /api/instances/{instanceId}/plugins/store
`[
    {
      "store": "string", <-- this is missing
      "name": "string",
      "description": "string",
      "version": "string",
      "uuid": "string"
    }
  ]`

**Comment by Multivit4min** [comment]
To download a plugin now only the UUID is required instead of store + name
