### ISSUE TITLE
Plugin Settings are being cached

### ISSUE THREAD

**Issue by cat24max** [alliance-apps/VeniceRCON-backend#21]
If you update a plugins meta.yaml with new options, these are not being displayed in the frontend even after a reinstall.

**To Reproduce**
Change plugin, update or reinstall plugin.

**Expected behavior**
Plugin options are refreshed instantly.

**Versions used**
 - Backend Version: prod
 - Node Version: Keine Ahnung

**Additional context**
Is net so geil

**Logs**
Nö

**Comment by Multivit4min** [comment]
already fixed in an earlier commit
